name: Security Scan
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    container:
      image: bridgecrew/checkov:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Checkov scan
        run: checkov -d /github/workspace --framework sast_python --soft-fail
