name: Security Scan
on: [push, pull_request]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    container:
      image: bridgecrew/checkov:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run Scan
        run: checkov -d /github/workspace --soft-fail
